### ISSUE TITLE
Configurable resolution chart export

### ISSUE THREAD

**Issue by DevTechProfile** [CXWorld/CapFrameX#140]
It would help if there are any export chart options where I could set for example resolution and export just the chart
would be also nice if there was a option to add custom picture

**Comment by elkimek** [comment]
I requested this. The other feature of "stamping" the exported chart with custom picture isn't that necessary but might come handy. Imagine exporting dozens of charts fro specific website and need to stamp it with site's logo. This exclude Photoshop post-processing. But it's not really *that* important.

The export feature on the other hand kinda is because again imagine you need dozens of charts of specific size for web-review and the in-build screenshot feature doesn't produce good quality. So you are left with snipping tools and the whole outcome depends on never resizing the CX window. If you could set straight like 800x400px as an export size, hit the export button/shortcut, it would do the trick.
