### ISSUE TITLE
Is there any way to start capture automatically?

### ISSUE THREAD

**Issue by Tualua** [CXWorld/CapFrameX#152]
Hi! Is there any way to force capture start automatically without pressing a key?

**Comment by awinnen** [comment]
What exactly do you mean by automatically?
You mean "programmatically" by an external application, or automatically in teams of starting the capture right after CX has been started?

**Comment by Tualua** [comment]
Hello! Right after CX has been started

пн, 14 дек. 2020 г. в 18:18, Alexander Winnen <notifications@github.com>:

**Comment by awinnen** [comment]
unfortunately this feature is currently not available.
We will discuss whether we can offer the feature in the future.

**Comment by Tualua** [comment]
Thank you!

**Comment by Taxxor90** [comment]
Is there any practical example where this would be helpful?

Upon starting CX, you can't just start a capture, it first needs to detect a running process and it needs to be the only one detected to start a capture.
I can't think of a usecase where a capture should start immediately after starting CX because that would mean you'd have to already be in a running game, tab out of it to start CX and then tab back in to do the things you want to have captured.
