### ISSUE TITLE
Process ignore list doesn't work for alacritty

### ISSUE THREAD

**Issue by farnoy** [CXWorld/CapFrameX#192]
I tried blacklisting [alacritty](https://github.com/alacritty/alacritty) in CapFrameX, but it had no effect on the overlay (it kept showing). I had to additionally ignore it in RTSS for the overlay to disappear.

For other apps that I blacklisted through CapFrameX, the effect was immediate and permanent, is there something different about alacritty? I think it's an OpenGL app, could that be it?

**Comment by Taxxor90** [comment]
If you want the overlay to not show on a specific app, you have to do that within RTSS. Our ignore list has no control over that.

The only thing our ignore list does is preventing PresentMon from recognizing the app as a target for capturing.
If you have apps that are not showing the overlay, that can't be because of our ignore list.
