### ISSUE TITLE
CapFrameX causes Rainbow Six: Raven Shield to crash

### ISSUE THREAD

**Issue by Ulver84** [CXWorld/CapFrameX#229]
Hi, the crash happens when one launches a mission. I've recorded a quick video: https://youtu.be/V1MCPh6Z8_k

The crash window shows the following information:

> OS: Windows NT 6.2 (Build: 9200)
> CPU: AuthenticAMD Unknown processor @ 3803 MHz with 2047MB RAM
> Video: AMD Radeon RX 6800 (10013)
> 
> General protection fault!
> 
> History: UD3DRenderDevice::SetRes <- UGameEngine::Draw <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- ClientTick <- UGameEngine::Tick <- UpdateWorld <- MainLoop
> 

CapFrameX is version 1.7.0.

Thanks, and do let me know if you need more information.

**Comment by Taxxor90** [comment]
Does it work with the RTSS overlay alone without CX running too?

**Comment by Taxxor90** [comment]
Just to be clear, the RTSS overlay isn't just enabled but also displays statistics from other sources than CX (like HWInfo or Afterburner) and the game won't crash?

**Comment by Ulver84** [comment]
1. With CX and RTSS running, and the RTSS overlay enabled, the game crashes once a mission has done loading (as seen in the YouTube video).
2. With CX and RTSS running, and the RTSS overlay disabled, the game doesn't crash once a mission has done loading.
3. The game also crashes, if RTSS is running and the overlay is enabled, if MSI afterburner is used instead of CX.

So, I suppose this is an RTSS crash more than CX. Curious on your input.

**Comment by Taxxor90** [comment]
> So, I suppose this is an RTSS crash more than CX. Curious on your input.

Yeah, like I mentioned in the other issue, we aren't doing anything besides telling RTSS what to show, so there couldn't be any  game crashing problems with the overlay that specifically come from CX.
That's why I was surprised by your initial comment that the game would work with RTSS overlay enabled but CX closed , that's why I specified the question of RTSS really showing an overlay instead of just being "on" in the system tray.

I mean, it's a fairly old game, like most of the ones in your other issue. Although RTSS has pretty good compatibility, running DX8 or even older APIs with it I'd expect it to either not work at all or giving troubles of some sort.

Well and with that, I'll close the issue, you could try to reach out in the RTSS forums though, maybe therere are ways to get it working, but that's out of our control.
