### ISSUE TITLE
CFX 1.7.x : Can't blacklist some applications

### ISSUE THREAD

**Issue by rphlrmblt** [CXWorld/CapFrameX#246]
With the CapFrameX 1.7.1 or even 1.7.2beta (latest build of 28th April), I can't add to blacklist some applications :

![image](https://github.com/CXWorld/CapFrameX/assets/4006281/baa733bd-5379-4019-a032-f6752f431297)

I've clicked a lot of time son the blue refresh button of Running Process without success.

It's Notepad3 from https://github.com/rizonesoft/Notepad3/releases

I've the same problem also for CoolerMaster+ and nPerf beta (closed beta).

Best regards.

**Comment by Taxxor90** [comment]
I don't see the app in your running proceses list so the blacklist works.

It has nothing tro do with the viosibility of the overlay, that is entirely controlleds by RTSS, not by us.

**Comment by rphlrmblt** [comment]
I can"t add the application because CapFrameX is not able to find it and allow me to add in blacklist. I'll try the RTSS tips !

**Comment by Taxxor90** [comment]
> I can"t add the application because CapFrameX is not able to find it and allow me to add in blacklist.

The only thing our blacklist does is preventing the apps from showing up in the list of processes to be captured.
If it's not showing up there to begin with, you obviously don't need to add it.

And again, that list has nothing to do with the overlay.

**Comment by rphlrmblt** [comment]
Ok, as the process isn't in this list : https://github.com/CXWorld/CapFrameX/blob/master/source/CapFrameX.Data/ProcessList/Processes.json it can't be changed in the CapFrameX interface if I understand well ?
I've used the RTSS trick and it works, nice to know it now.

**Comment by Taxxor90** [comment]
> Ok, as the process isn't in this list : https://github.com/CXWorld/CapFrameX/blob/master/source/CapFrameX.Data/ProcessList/Processes.json it can't be changed in the CapFrameX interface if I understand well ?

Even if it was on that list, it wouldn't change anything about the overlay because, as I already said, it doesn't have anything to do with the overlay.

The running processes list is for apps that are detected by the capture service as apps that can be captured.
You don't have to do anything if the app isn't even recognised as one that could be captured.
The capture service has it's own internal filters as what app is most likely a 3D app that could be captured and what isn't.

The ignore list exists, so that you can manually move unwanted apps that appear in the running processes list and preventing you from just starting a capture.

**Comment by rphlrmblt** [comment]
Thanks for the explanations what should be readable on a Wiki to avoid this kind of bug report. As I'll close the bug, these comments won't be directly visible.

Best regards.

**Comment by Taxxor90** [comment]
What the running processes and ignore list does is explained in the manual here on GitHub.
