### ISSUE TITLE
Feature request : Add PMD Metrics

### ISSUE THREAD

**Issue by AndLain2501** [CXWorld/CapFrameX#283]
Hello,
Thank you for your amazing software, I want move from AfterBurner to CapframeX (Powernetics V2) for my benchmark measurement.

Is it possible to add PMD power consumption to the statistics that can be displayed in REPORT?

Can a after the decimal point be added to the PMD power consumption?
For example, “35W” becomes “35.4W”.

![cx-request-image](https://github.com/user-attachments/assets/5283db49-3bc0-427b-b17d-a30f42b9e94f)

Thank you and have a nice day,

**Comment by Taxxor90** [comment]
[This version](https://archive.capframex.com/builds/release/1.7.3/26/3a18c351d32b0384ccafad4131575eb26fe9c73c_installer.zip) has a toggle on the Report page that changes the CPU and GPU power metrics to use the PMD values. CPU and GPU FPS/10W are also affected by this.
Unfortunately because of the way the report entries are generated, I couldn't get them to update automatically after changing the option so I had to clear the list every time you switch between PMD and Sensor values
